USE [master]
GO
/****** Object:  Database [webOnline]    Script Date: 4/26/2021 9:38:23 PM ******/
CREATE DATABASE [webOnline]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'webOnline', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\webOnline.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'webOnline_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\webOnline_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [webOnline] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [webOnline].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [webOnline] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [webOnline] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [webOnline] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [webOnline] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [webOnline] SET ARITHABORT OFF 
GO
ALTER DATABASE [webOnline] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [webOnline] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [webOnline] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [webOnline] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [webOnline] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [webOnline] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [webOnline] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [webOnline] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [webOnline] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [webOnline] SET  ENABLE_BROKER 
GO
ALTER DATABASE [webOnline] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [webOnline] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [webOnline] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [webOnline] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [webOnline] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [webOnline] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [webOnline] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [webOnline] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [webOnline] SET  MULTI_USER 
GO
ALTER DATABASE [webOnline] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [webOnline] SET DB_CHAINING OFF 
GO
ALTER DATABASE [webOnline] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [webOnline] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [webOnline] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [webOnline] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [webOnline] SET QUERY_STORE = OFF
GO
USE [webOnline]
GO
/****** Object:  Table [dbo].[News_Category]    Script Date: 4/26/2021 9:38:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[News_Category](
	[IDCategory] [int] IDENTITY(1,1) NOT NULL,
	[CateName] [nvarchar](50) NULL,
	[cLink] [nvarchar](50) NULL,
	[cOrder] [int] NULL,
	[cActive] [bit] NULL,
 CONSTRAINT [PK_dbo.News_Category] PRIMARY KEY CLUSTERED 
(
	[IDCategory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[News_Category] ON 

INSERT [dbo].[News_Category] ([IDCategory], [CateName], [cLink], [cOrder], [cActive]) VALUES (1, N'Xa hoi', N'xaphoi', 1, 1)
INSERT [dbo].[News_Category] ([IDCategory], [CateName], [cLink], [cOrder], [cActive]) VALUES (2, N'tintuc', N'tin-tuc', 2, 1)
INSERT [dbo].[News_Category] ([IDCategory], [CateName], [cLink], [cOrder], [cActive]) VALUES (3, N'Tin Tuc su kien', N'Tintuc-sukien', 3, 1)
INSERT [dbo].[News_Category] ([IDCategory], [CateName], [cLink], [cOrder], [cActive]) VALUES (4, N'Phim anh', N'phim-anh', 10, 1)
SET IDENTITY_INSERT [dbo].[News_Category] OFF
GO
/****** Object:  StoredProcedure [dbo].[spgetList_News_Category]    Script Date: 4/26/2021 9:38:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[spgetList_News_Category]
as BEGIN
SELECT*FROM News_Category
END
GO
USE [master]
GO
ALTER DATABASE [webOnline] SET  READ_WRITE 
GO
