//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Category
    {
        public int IDCategory { get; set; }
        public string CateName { get; set; }
        public string cLink { get; set; }
        public Nullable<int> cOrder { get; set; }
        public Nullable<bool> cActive { get; set; }
    }
}
